.\" Title: watch-file 
.\" Author: Josh Brunton 
.\" Date: 2024-06-06 
.\"
.TH WATCH_FILE 1 "2024-06-06" "1.0" "watch-file" "User Commands"
.SH NAME
watch-file - watch a file for changes
.SH SYNOPSIS
.B watch-file 
FILE [{\f--head|-h|--tail|-t\fR}=10] [--no-header] [--no-footer] [{--raw|-r}] [{--interval|-i}=1000] [{--diff|-d}] [{--output|-o} PATH] [--output-mode (append|overwrite)] [{--quiet|-q}]
.SH DESCRIPTION
\fBwatch-file\fR watches a file for changes and outputs if its contents have been changed while running. 
.PP
\fBwatch-file\fR does not hold onto the file - it will only open it to read at the interval requested. 
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-head\fR \fIvalue\fR
Output only the first n lines of the file. n must be a 32-bit integer. Default 10.
.TP
\fB\-t\fR, \fB\-\-tail\fR \fIvalue\fR
Output only the last n lines of the file. n must be a 32-bit integer. Default 10.
.TP
\fB\-\-no-header\fR 
Skip outputting the header (which shows the filename and time of read)
.TP
\fB\-\-no-footer\fR 
Skip outputting the footer (which shows the filename and time of read)
.TP
\fB\-r\fR, \fB\-\-raw\fR
Equivalent to passing --no-header and --no-footer together.
.TP
\fB\-i\fR, \fB\-\-interval\fR \fIvalue\fR
How often the program should check the file for updates, in milliseconds. Must be an unsigned 64-bit integer. Default 1000.
.TP
\fB\-d\fR, \fB\-\-diff\fR 
Instead of displaying the pure contents of the file, generate a patch from the previous version each time it changes.
.TP
\fB\-o\fR, \fB\-\-output\fR \fIvalue\fR
A file to output to. See also \fI--output-mode\fR. 
.TP
\fB\-\-output-mode\fR \fI[append|overwrite]\fR
When passing the \fI--output\fR flag, should we append to the file when the watched file is changed, or overwrite the file? Default behaviour is append. Only has effect when uassed with \fI--output\fR.
.TP
\fB\-q\fR, \fB\-\-quiet\fR
Don't output anything to the console. Only useful when used with \fI--output\fR.
.SH AUTHOR
Written by Josh Brunton.
